on:
  workflow_dispatch:


name: Test

jobs:
  test:
    runs-on: windows-2022
    steps:
      -
        name: Find dumpbin
        shell: pwsh
        run: |
          $vsPath = & vswhere.exe -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          $vcToolsVersion = Get-Content -LiteralPath "$vsPath\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt" -TotalCount 1
          $dumpBin32 = "$vsPath\VC\Tools\MSVC\$vcToolsVersion\bin\Hostx86\x86\dumpbin.exe"
          $dumpBin64 = "$vsPath\VC\Tools\MSVC\$vcToolsVersion\bin\HostX64\x64\dumpbin.exe"
          Write-Host '### 32 bits'
          Get-ChildItem -LiteralPath $dumpBin32
          & $dumpBin32 /?
          Write-Host '### 64 bits'
          Get-ChildItem -LiteralPath $dumpBin64
          & $dumpBin64 /?